---
title: "Team Performance Starter Notebook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

rm(list=ls())

```

```{r}



project_name = 'sports/nba/team_perf_by_quarter'

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
repo_path = file.path(substr(getwd(),0,gregexpr(pattern = project_name ,
                                                getwd())[[1]][1]-2),
                      project_name)

source(file.path(repo_path,
                 'code',
                 'utilities',
                 'load_directories.r'),
       local = knitr::knit_global())


```

```{r}

p <- c("tidyverse",
       "lubridate",
       "ggplot2",
       "reticulate")

load_all_packages(p)

```

This cell establishes how the averages will be done. Leave these as parameters,
as customers are unsure how they want to calculate at this time. For my live 
model, I use 70% of the average as from the last 10 games, 30% from season-long
cumulative averages.

```{r}

# w_vec = c(rk,cummean) ... should add to 1
w_vec = c(.7,.3)
k = 10

```

```{r}



```


